# -*- coding: utf-8 -*-
"""ai-model-implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QBs3-Iq2Bf4-wPI7RiJIsA6rVODiBLT2
"""

import nbformat

nb = nbformat.read("ai-model-implementation.ipynb", as_version=4)
if "widgets" in nb["metadata"]:
    del nb["metadata"]["widgets"]

nbformat.write(nb, "ai-model-implementation.ipynb")

"""# WEEK 2 - Model Implementation (Small Models)
# Steps:
# 1. Load dataset
# 2. Load small models
# 3. Generate predictions
# 4. Save results

# Install Libraries for machine learning
"""

!pip install transformers==4.38.0 accelerate datasets torch

"""# 2. Import data and plotting helpers"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# Load the SQuAD dataset (small subset)"""

!pip install datasets
from datasets import load_dataset
dataset = load_dataset("squad")
train_50 = dataset["train"].select(range(50))

print(train_50)

train_df = dataset['train'].to_pandas()
train_df

train_df.head( )

"""# Loading models & tokenizers (implied)"""

# -------------------------------
# 1️⃣ Install required packages
# -------------------------------
!pip install --quiet transformers datasets huggingface_hub accelerate

# -------------------------------
# 2️⃣ Set Hugging Face token
# -------------------------------
import os

os.environ["HUGGINGFACE_TOKEN"] = "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"  # <-- replace with your token

# -------------------------------
# 3️⃣ Login to Hugging Face
# -------------------------------
from huggingface_hub import login
login(token=os.environ["HUGGINGFACE_TOKEN"])

# -------------------------------
# 4️⃣ Load TinyLlama model + tokenizer
# -------------------------------
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(model_name, use_auth_token=True)
model = AutoModelForCausalLM.from_pretrained(model_name, use_auth_token=True, device_map="auto")

# -------------------------------
# 5️⃣ Quick test i

"""#### This imports Hugging Face’s pipeline() —
It makes using models very easy (text-generation, translation, etc).
"""

from transformers import pipeline

llama = None
qwen = None

try:

    print("Attempting to load LLaMA 3 model...")
    llama = pipeline(
        "text-generation",
        model="TinyLlama/TinyLlama-1.1B-Chat-v1.0", # Corrected model ID
        device_map="cpu" # Changed to 'cpu'
    )
    print("LLaMA  model loaded successfully.")
except OSError as e:
    print(f"Error loading LLaMA 3 model: {e}")
    if "TinyLlama/TinyLlama-1.1B-Chat-v1.0" in str(e):
        print("This is likely due to the gated access for LLaMA models. Please ensure you have visited "
              "https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0 and accepted the terms and conditions.")
    print("Skipping LLaMA  model loading.")

try:
    # Qwen small model (0.5B)
    print("Attempting to load Qwen model...")
    qwen = pipeline(
        "text-generation",
        model="Qwen/Qwen1.5-0.5B",
        device_map="cpu" # Changed to 'cpu'
    )
    print("Qwen model loaded successfully.")
except OSError as e:
    print(f"Error loading Qwen model: {e}")
    print("Skipping Qwen model loading.")

if llama is not None:
    print("LLaMA model object is available.")
else:
    print("LLaMA model object is NOT available.")

if qwen is not None:
    print("Qwen model object is available.")
else:
    print("Qwen model object is NOT available.")

"""#### Import required libraries
    torch → Needed for model tensors (PyTorch)
    pipeline → Easy interface to load and generate text

1. Import libraries --> Bring PyTorch and pipeline         
2. Load model       --> Load TinyLlama automatically     
3. Set messages     -->System and user chat messages      
4. Generate output ---> Model writes pirate-style answer
5. Print result     ---> Shows only model reply
"""

import torch
from transformers import pipeline

model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0" # Corrected model ID
pipe = pipeline(
    "text-generation",
    model=model_id,
    torch_dtype=torch.bfloat16,
    device_map="auto",
)
messages = [
    {"role": "system", "content": "You are a pirate chatbot who always responds in pirate speak!"},
    {"role": "user", "content": "Who are you?"},
]
outputs = pipe(
    messages,
    max_new_tokens=256,
)
print(outputs[0]["generated_text"][-1])

"""#### Construction of prompts manually & loading tokenizers and generation output"""

def generate_prompt(context, question):
    return (
        f"Answer the question based on the passage.\n"
        f"Passage: {context}\n"
        f"Question: {question}\n"
        f"Answer:"
    )
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("model-name")
model = AutoModelForCausalLM.from_pretrained("model-name", device_map="auto")
inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
outputs = model.generate(**inputs, max_new_tokens=64)
answer = tokenizer.decode(outputs[0], skip_special_tokens=True)

"""pandas --> for DataFrame

time → for measuring how long model takes

Loads SQuAD dataset
Takes 3 samples and Creating questions,
  Sends to LLaMA and Qwen,
Collects answers + time

Saves results in DataFrame
and Printing comparison
"""

import pandas as pd
import time
from datasets import load_dataset

# Ensure dataset is loaded for train_df
dataset = load_dataset("squad")
train_df = dataset['train'].to_pandas()

def generate_prompt(context, question):
    return f"Answer the question based on the passage.\nPassage: {context}\nQuestion: {question}\nAnswer:"

results = []

# Reduced to 3 rows for quicker execution
for i in range(3):
    ctx = train_df.loc[i, 'context']
    qn = train_df.loc[i, 'question']
    true_ans = train_df.loc[i, 'answers']

    prompt = generate_prompt(ctx, qn)

    # - LLaMA generation --
    # Use the 'llama' pipeline object which was successfully loaded in a previous cell
    if 'llama' in globals() and llama is not None:
        t1 = time.time()
        output = llama(prompt, max_new_tokens=50)
        llama_out = output[0]['generated_text'] if output else "Generation failed"
        llama_time = time.time() - t1
    else:
        llama_out = "LLaMA not loaded"
        llama_time = 0.0

    # - Qwen generation (optional, remove if not needed) -
    if 'qwen' in globals() and qwen is not None:
        t2 = time.time()
        output = qwen(prompt, max_new_tokens=50)
        qwen_out = output[0]['generated_text'] if output else "Generation failed"
        qwen_time = time.time() - t2
    else:
        qwen_out = "Qwen not loaded"
        qwen_time = 0.0

    results.append({
        "question": qn,
        "true_answer": true_ans,
        "llama_answer": llama_out,
        "qwen_answer": qwen_out,
        "llama_time": llama_time,
        "qwen_time": qwen_time
    })

df_out = pd.DataFrame(results)
print(df_out.head())

from google.colab import files

files.download("model_outputs.csv")

"""creates a bar graph:

X-axis → Model names

Y-axis → Average time

Two bars → LLaMA and Qwen

You can visually see which model is faster/slower
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate average times
avg_llama_time = df_out['llama_time'].mean()
avg_qwen_time = df_out['qwen_time'].mean()

print(f"Average LLaMA generation time: {avg_llama_time:.2f} seconds")
print(f"Average Qwen generation time: {avg_qwen_time:.2f} seconds")

# Create a DataFrame for plotting
times_df = pd.DataFrame({
    'Model': ['LLaMA', 'Qwen'],
    'Average Time (seconds)': [avg_llama_time, avg_qwen_time]
})

# Plotting
plt.figure(figsize=(8, 5))
sns.barplot(x='Model', y='Average Time (seconds)', data=times_df, palette='viridis')
plt.title('Average Generation Time Comparison: LLaMA vs Qwen')
plt.ylabel('Average Time (seconds)')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""### F1 Score and Exact Match Metrics

**Exact Match (EM)** is a strict metric that measures the percentage of predictions that match *exactly* one of the ground-truth answers.

**F1 Score** is a more lenient metric that measures the average overlap between the prediction and the ground-truth answer. It is calculated as the harmonic mean of precision and recall. For question answering, it's typically calculated over the words of the predicted and true answers, allowing for partial credit.

Evaluation — Exact Match (EM) and F1

code computes EM and F1 scores for each model:

Exact Match (EM): whether the predicted answer exactly matches one of the ground-truth answers.

F1 score: token-level overlap between prediction and the best matching true answer (balances precision and recall).

Code collects scores into lists like llama_f1_scores, llama_em_scores, qwen_f1_scores, qwen_em_scores.
"""

import re
import collections

def normalize_answer(s):
    """Lower text and remove punctuation, articles and extra whitespace."""
    def remove_articles(text):
        return re.sub(r'\b(a|an|the)\b', ' ', text)
    def white_space_fix(text):
        return ' '.join(text.split())
    def remove_punc(text):
        return re.sub(r'[\.,\/#!$%^&\*;:{}=\-_`~()@+\[\]]', '', text)
    def lower(text):
        return text.lower()
    return white_space_fix(remove_articles(remove_punc(lower(s))))

def get_tokens(s):
    if not s: return []
    return normalize_answer(s).split()

def compute_exact(a_gold, a_pred):
    return int(normalize_answer(a_gold) == normalize_answer(a_pred))

def compute_f1(a_gold, a_pred):
    gold_tokens = get_tokens(a_gold)
    pred_tokens = get_tokens(a_pred)
    common = collections.Counter(gold_tokens) & collections.Counter(pred_tokens)
    num_common = sum(common.values())
    if len(gold_tokens) == 0 or len(pred_tokens) == 0:
        # If either is no-answer, then F1 is 1 if they agree, 0 otherwise
        return int(gold_tokens == pred_tokens)
    if num_common == 0:
        return 0
    precision = num_common / len(pred_tokens)
    recall = num_common / len(gold_tokens)
    return (2 * precision * recall) / (precision + recall)

llama_f1_scores = []
llama_em_scores = []
qwen_f1_scores = []
qwen_em_scores = []

for index, row in df_out.iterrows():
    # Extract true answers (handling the list of answers in the dict)
    true_answers = row['true_answer']['text']

    # Handle cases where true_answers might be empty or missing
    if not true_answers: # Skip if no true answers are provided
        continue

    # LLaMA evaluation
    llama_pred = row['llama_answer'].split('Answer: ')[-1].strip() if 'Answer: ' in row['llama_answer'] else row['llama_answer'].strip()

    # Find best F1 and EM score against all true answers
    best_llama_f1 = 0
    best_llama_em = 0
    for t_ans in true_answers:
        best_llama_f1 = max(best_llama_f1, compute_f1(t_ans, llama_pred))
        best_llama_em = max(best_llama_em, compute_exact(t_ans, llama_pred))
    llama_f1_scores.append(best_llama_f1)
    llama_em_scores.append(best_llama_em)

    # Qwen evaluation
    qwen_pred = row['qwen_answer'].split('Answer: ')[-1].strip() if 'Answer: ' in row['qwen_answer'] else row['qwen_answer'].strip()

    # Find best F1 and EM score against all true answers
    best_qwen_f1 = 0
    best_qwen_em = 0
    for t_ans in true_answers:
        best_qwen_f1 = max(best_qwen_f1, compute_f1(t_ans, qwen_pred))
        best_qwen_em = max(best_qwen_em, compute_exact(t_ans, qwen_pred))
    qwen_f1_scores.append(best_qwen_f1)
    qwen_em_scores.append(best_qwen_em)

# Calculate averages
avg_llama_f1 = sum(llama_f1_scores) / len(llama_f1_scores) if llama_f1_scores else 0
avg_llama_em = sum(llama_em_scores) / len(llama_em_scores) if llama_em_scores else 0
avg_qwen_f1 = sum(qwen_f1_scores) / len(qwen_f1_scores) if qwen_f1_scores else 0
avg_qwen_em = sum(qwen_em_scores) / len(qwen_em_scores) if qwen_em_scores else 0

print(f"--- Average Scores ---")
print(f"LLaMA F1: {avg_llama_f1:.2f}")
print(f"LLaMA Exact Match: {avg_llama_em:.2f}")
print(f"Qwen F1: {avg_qwen_f1:.2f}")
print(f"Qwen Exact Match: {avg_qwen_em:.2f}")